#### This is like a Production code - A webpage that accepts the input Pclass, SibSp, Parch, Fare, Age, Sex, Embarked & predicts outcome
- We need to again write the same series of steps that we wrote during training i.e. to do encode, scale, etc. that we did during the development.
- If we make some change in development, again we need to make the same change in production.

In [2]:
import pickle
import numpy as np

OneHotEncoder_SexObj = pickle.load(open('models/OneHotEncoder_SexObj.pk1','rb'))
OneHotEncoder_EmbarkedObj = pickle.load(open('models/OneHotEncoder_EmbarkedObj.pk1','rb'))
DecisionTreeClassifierObj = pickle.load(open('models/DecisionTreeClassifierObj.pk1','rb'))

MinMaxScaler_Pclass_Obj = pickle.load(open('models/MinMaxScaler_Pclass_Obj.pk1','rb'))
MinMaxScaler_Age_Obj = pickle.load(open('models/MinMaxScaler_Age_Obj.pk1','rb'))
MinMaxScaler_SibSp_Obj = pickle.load(open('models/MinMaxScaler_SibSp_Obj.pk1','rb'))
MinMaxScaler_Parch_Obj = pickle.load(open('models/MinMaxScaler_Parch_Obj.pk1','rb'))
MinMaxScaler_Fare_Obj = pickle.load(open('models/MinMaxScaler_Fare_Obj.pk1','rb'))

In [3]:
# Assume user input Pclass, SibSp, Parch, Fare, Age, Sex, Embarked

test_input = np.array([2,0,0,10.5,31.0,'male','S'],dtype=object).reshape(1,7)
test_input

array([[2, 0, 0, 10.5, 31.0, 'male', 'S']], dtype=object)

#### Perform the preprocessng steps

In [7]:
test_input_Pclass = MinMaxScaler_Pclass_Obj.transform(test_input[:,0].reshape(1,1))
test_input_SibSp = MinMaxScaler_SibSp_Obj.transform(test_input[:,1].reshape(1,1))
test_input_Parch = MinMaxScaler_Parch_Obj.transform(test_input[:,2].reshape(1,1))
test_input_Fare = MinMaxScaler_Fare_Obj.transform(test_input[:,3].reshape(1,1))
test_input_Age = MinMaxScaler_Age_Obj.transform(test_input[:,4].reshape(1,1))
test_input_Sex = OneHotEncoder_SexObj.transform(test_input[:,5].reshape(1,1))
test_input_Embarked = OneHotEncoder_EmbarkedObj.transform(test_input[:,6].reshape(1,1))

test_input_transformed = np.concatenate((test_input_Pclass,test_input_SibSp,test_input_Parch,test_input_Fare,test_input_Age,test_input_Sex,
                                        test_input_Embarked),axis=1)
test_input_transformed

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0.5       , 0.        , 0.        , 0.02049464, 0.3842674 ,
        0.        , 1.        , 0.        , 0.        , 1.        ]])

In [9]:
# Predict the outcome

DecisionTreeClassifierObj.predict(test_input_transformed)

array([1], dtype=int64)