#### Feature Scaling - More detailed explanation in 13_Feature_Scaling file.
- There are different types of scaling techniques like Standard Scaler, MinMaxScaler, Robust Scaler, Max Abs Scaler.
- Why do we do Feature scaling?
-
- Ex:-
- experience 
- Emp1 = 3y
- Emp2 = 5y
- 
- salary
- y1 = 50,000
- y2 = 90,000
-
- If we use any Model that calcualtes Eucladian distance >> example, K Means >> The Algorithms will be more inclined towards salary, since the values are very high relative to experience.
- Since we want our model to give equal weightage to experience and salary while creating the model, we use scaling and bring both the Features to same level.

#### Standardization Examples - Standard Scaler - (Z-score normalization)
- Not good with outliers.
- The transformed data will have Mean = 0 and SD = 1
- More details in 13_Feature_Scaling file.

In [95]:
import pandas as pd

Social_Network_Ads_DF = pd.read_csv(r"C:\Users\ACER\Desktop\Kranthi\DataScience_Desktop\MachineLearningFiles\Social_Network_Ads.csv")
Social_Network_Ads_DF.head(5)
Social_Network_Ads_DF.shape

(400, 5)

In [67]:
# Social_Network_Ads_DF_Features, take only Age, EstimatedSalary and Purchased column for our Model.

Social_Network_Ads_DF_Features = Social_Network_Ads_DF.iloc[:,2:]
#x = Social_Network_Ads_DF.drop(columns=['Purchased'], axis=0)
#y = Social_Network_Ads_DF.Purchased

In [75]:
# Prepare the train and test data

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(Social_Network_Ads_DF_Features.iloc[:,0:2],Social_Network_Ads_DF_Features.Purchased)
#x_train, x_test, y_train, y_test = train_test_split(Social_Network_Ads_DF_Features[['Age','EstimatedSalary']],Social_Network_Ads_DF_Features.Purchased)

In [79]:
y_test.head(3)

241    0
283    1
13     0
Name: Purchased, dtype: int64

In [81]:
# Perform Standard Scaler

from sklearn.preprocessing import StandardScaler

# Create StandardScaler object.
StandardScalerObj = StandardScaler()

# Train data
StandardScalerObj.fit(x_train)
# Now Mean and SD are calculated on x_train data, and then the formula is applied while transforming the data

# Check Mean and SD calculated by StandardScaler
StandardScalerObj.mean_

array([3.80466667e+01, 7.08666667e+04])

In [83]:
# Transform train and test data - Apply the formula X_scaled = (X - mean) / standard_deviation
# Model applies the StandardScaler formula using the mean and SD calculated in above step.

x_train_scaled = StandardScalerObj.transform(x_train)
x_test_scaled = StandardScalerObj.transform(x_test)

In [93]:
x_test

Age  EstimatedSalary
241   38            59000
283   52            21000
13    32            18000
294   35            57000
89    35            50000
..   ...              ...
104   19            21000
16    47            25000
388   47            34000
126   42            65000
356   54            70000

[100 rows x 2 columns]

In [89]:
# Check the transformed(scaled) data 

x_train_scaled
# Output is in numpy array format

array([[-0.29710102,  0.18172469],
       [ 2.04330092,  0.15209567],
       [-0.68716801, -0.08493654],
       [-0.68716801, -0.38122681],
       [-1.17475175,  1.39651477],
       [ 0.19048271,  0.03357956],
       [-0.10206753,  0.27061177],
       [-0.00455078,  1.21874062],
       [ 1.94578417,  0.89282133],
       [ 0.19048271,  0.12246664],
       [-0.68716801,  1.39651477],
       [ 1.06813344, -0.9441783 ],
       [-1.17475175,  0.44838593],
       [-0.29710102, -0.97380733],
       [-0.78468476,  1.90020822],
       [ 0.09296597, -0.35159778],
       [ 1.45820043, -1.09232344],
       [ 1.36068369,  1.9890953 ],
       [-0.78468476, -1.65527494],
       [ 2.14081767, -0.85529123],
       [-0.29710102, -0.38122681],
       [ 1.06813344,  0.50764398],
       [-0.68716801,  0.53727301],
       [ 0.09296597,  0.74467619],
       [ 0.28799946, -0.32196875],
       [-0.10206753, -0.2627107 ],
       [ 1.06813344,  0.44838593],
       [-0.00455078,  0.00395054],
       [ 0.87309995,

In [17]:
# Convert the data to DataFrame

x_train_scaled_DF = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled_DF = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [19]:
# After the data is scaled using the formula, calculate mean of the transformed Age and EstimatedSalary

import numpy as np
np.round(x_train_scaled_DF.describe(),1)
# x_train_scaled_DF.describe()
# We can see the Mean and SD are 0 and 1 respectively.

Age  EstimatedSalary
count  300.0            300.0
mean     0.0              0.0
std      1.0              1.0
min     -1.9             -1.6
25%     -0.8             -0.8
50%     -0.1             -0.1
75%      0.8              0.5
max      2.1              2.3

In [125]:
np.round(x_test_scaled_DF.describe(),1)

Age  EstimatedSalary
count  100.0            100.0
mean    -0.1              0.0
std      0.9              1.0
min     -1.9             -1.6
25%     -0.8             -0.7
50%     -0.0              0.1
75%      0.4              0.5
max      2.0              2.2

In [41]:
# Scaled Feature
# Multiple Linear Regression

from sklearn.linear_model import LinearRegression

# Crate Separate object to use for scaled and non-scaled data
LinearRegression_ScaledData = LinearRegression()
LinearRegression_NonScaledData = LinearRegression()

LinearRegression_ScaledData.fit(x_train_scaled,y_train)
LinearRegression_NonScaledData.fit(x_train,y_train)

LinearRegression()

In [119]:
y_predict_sales_WithScaledData = LinearRegression_ScaledData.predict(x_test_scaled_DF)
y_predict_sales_WithoutScaledData = LinearRegression_ScaledData.predict(x_test)

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(
C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


In [123]:
y_predict_sales_WithScaledData
y_predict_sales_WithoutScaledData

array([ 8124.36652455,  2902.73437754,  2484.58987652,  7848.49730298,
        6885.89548043,  4133.08417062, 12390.11788436,  3168.80208924,
        8952.53427555,  2070.36597945,  7849.89751867, 13209.3242549 ,
       11011.89194905,  9911.77558043, 11281.60022156, 11009.93164707,
        7982.93137453, 20499.27545587,  4554.30914617,  3860.01538044,
        3581.06568434,  7161.48465887,  8669.94401864, 14861.73915295,
       10322.07887355, 15411.51729412,  5926.65417556, 11430.87657948,
       19812.82289803,  6342.8383746 ,  6886.73560985,  5792.50014715,
       19812.5428549 ,  6479.7928344 , 10871.85701472,  8949.45380102,
       11009.65160394,  3035.48819025, 11559.42974511,  7849.05738926,
        4001.73057361,  5923.01361475,  2763.81961577, 18028.21427355,
        8813.0594275 ,  8121.56609316, 13080.49104614,  2206.48030984,
        9912.89575298,  5923.01361475,  9773.70094807,  9911.21549415,
        5240.48166086,  3719.42035983, 19815.62332943,  9774.54107749,
      

### Normalizatoin Examples - MinMaxScaler
- MinMaxScaling - is not good with outliers
- Range is between 0 and 1
- More details in 13_Feature_Scaling file.

In [194]:
import pandas as pd

Social_Network_Ads_DF = pd.read_csv(r"C:\Users\ACER\Desktop\Kranthi\DataScience_Desktop\MachineLearningFiles\Social_Network_Ads.csv")
Social_Network_Ads_DF.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [261]:
# Prepare the Features to be used in the model.

x = Social_Network_Ads_DF.drop(columns=['Purchased','Gender','User ID'],axis=0)
y = Social_Network_Ads_DF.Purchased

In [202]:
# Prepare the train and test data

x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train

Age  EstimatedSalary
356   54            70000
113   37            55000
311   39            96000
373   59           130000
26    49            28000
..   ...              ...
252   48           134000
91    30           116000
303   37            79000
296   42            73000
243   56           104000

[300 rows x 2 columns]

In [206]:
# Create the model for MinMaxScaling

from sklearn.preprocessing import MinMaxScaler

# Create MinMaxScaler object
MinMaxScalerObj = MinMaxScaler()

# Train with the traning data
MinMaxScalerObj.fit(x_train)

MinMaxScaler()

In [222]:
# Various attributes on MinMaxScaler Object

MinMaxScalerObj.min_
MinMaxScalerObj.scale_
MinMaxScalerObj.data_min_
MinMaxScalerObj.data_max_
MinMaxScalerObj.data_range_
MinMaxScalerObj.n_features_in_

2

In [238]:
# Transform the data

x_train_scaled = MinMaxScalerObj.transform(x_train)
x_test_scaled = MinMaxScalerObj.transform(x_test)
x_test_scaled
# Output will be in numpy array format

array([[0.69047619, 0.68148148],
       [0.64285714, 0.08148148],
       [0.54761905, 0.41481481],
       [0.33333333, 0.02222222],
       [0.4047619 , 0.33333333],
       [0.45238095, 0.34814815],
       [0.73809524, 0.52592593],
       [0.33333333, 0.75555556],
       [0.02380952, 0.51851852],
       [0.9047619 , 0.33333333],
       [0.        , 0.21481481],
       [0.80952381, 1.        ],
       [0.83333333, 0.14074074],
       [0.21428571, 0.51111111],
       [0.23809524, 0.51111111],
       [0.54761905, 0.42222222],
       [0.64285714, 0.85925926],
       [0.07142857, 0.39259259],
       [0.66666667, 0.32592593],
       [0.45238095, 0.31111111],
       [0.5       , 0.32592593],
       [0.69047619, 0.72592593],
       [0.69047619, 0.95555556],
       [0.66666667, 0.6       ],
       [0.28571429, 0.54814815],
       [0.04761905, 0.4962963 ],
       [0.02380952, 0.04444444],
       [0.54761905, 0.26666667],
       [0.97619048, 0.94814815],
       [0.97619048, 0.54074074],
       [0.

In [248]:
# Check the minimum and maximum values in transformed data.

x_train_scaled_DF = pd.DataFrame(x_train_scaled)
x_test_scaled_DF = pd.DataFrame(x_test_scaled)
print('Min value in x_train_scaled_DF is ', x_train_scaled_DF.min())
print('Max value in x_test_scaled_DF is ', x_test_scaled_DF.max())

Min value in x_train_scaled_DF is  0    0.0
1    0.0
dtype: float64
Max value in x_test_scaled_DF is  0    1.0
1    1.0
dtype: float64


- ### Robust Scaling
- Xnew = X - Median/IQR
- IQR = Q3-Q1
- Good with outliers but not good with sparse data(data with more zeros/nulls)
- More details in 13_Feature_Scaling file.

In [265]:
import pandas as pd

Social_Network_Ads_DF = pd.read_csv(r"C:\Users\ACER\Desktop\Kranthi\DataScience_Desktop\MachineLearningFiles\Social_Network_Ads.csv")
Social_Network_Ads_DF.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [267]:
# Prepare the Features to be used in the model.

x = Social_Network_Ads_DF.drop(columns=['Purchased','Gender','User ID'],axis=0)
y = Social_Network_Ads_DF.Purchased

In [271]:
# Prepare the train and test data

x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.head(3)

Age  EstimatedSalary
292   55            39000
119   41            59000
107   27            89000

In [284]:
# Create the model for RobustScaler

from sklearn.preprocessing import RobustScaler

# Create object for RobustScaler
RobustScalerObj = RobustScaler()

# Train with the traning data
RobustScalerObj.fit(x_train)

RobustScaler()

In [328]:
# Various attributes on RobustScaler Object

RobustScalerObj.center_
#RobustScalerObj.scale_
#RobustScalerObj.n_features_in_
#RobustScalerObj.feature_names_in_

array([3.7e+01, 6.8e+04])

In [308]:
# Transform the data

x_train_scaled = RobustScalerObj.transform(x_train)
x_test_scaled = RobustScalerObj.transform(x_test)
x_test_scaled
# Output will be in numpy array format

array([[ 0.5625    , -0.88888889],
       [-0.0625    ,  1.28888889],
       [ 1.1875    , -0.17777778],
       [-0.625     ,  0.44444444],
       [-0.3125    , -1.11111111],
       [-0.375     ,  0.13333333],
       [-0.5       ,  0.15555556],
       [ 0.25      ,  0.08888889],
       [ 0.3125    ,  0.11111111],
       [-0.25      , -0.55555556],
       [ 0.875     ,  1.73333333],
       [ 0.5625    ,  0.44444444],
       [ 1.4375    , -0.48888889],
       [ 0.25      ,  0.06666667],
       [-0.875     ,  0.31111111],
       [-0.5       ,  0.33333333],
       [-0.5       , -0.55555556],
       [ 0.625     , -0.42222222],
       [-0.8125    , -1.08888889],
       [-0.9375    , -1.11111111],
       [-1.0625    ,  0.31111111],
       [ 0.875     ,  1.46666667],
       [ 0.        , -0.77777778],
       [-0.5       , -0.15555556],
       [ 0.5625    , -1.02222222],
       [-1.0625    ,  0.31111111],
       [-0.125     , -0.2       ],
       [ 0.5625    , -1.        ],
       [-0.5625    ,

In [336]:
# Convert the array to DataFrame

x_test_scaled_DF = pd.DataFrame(x_test_scaled, columns = x_test.columns)
sorted = x_test_scaled_DF.sort_values(by='Age')

#### MaxAbs Scaling
- Scales data to the range [-1, based on the maximum absolute value in each feature. 
- x_new = xi / |xmax|
- Good with sparse data(data with more zeros/nulls)
- Not good with outliers

In [338]:
import pandas as pd

Social_Network_Ads_DF = pd.read_csv(r"C:\Users\ACER\Desktop\Kranthi\DataScience_Desktop\MachineLearningFiles\Social_Network_Ads.csv")
Social_Network_Ads_DF.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [340]:
# Prepare the Features to be used in the model.

x = Social_Network_Ads_DF.drop(columns=['Purchased','Gender','User ID'],axis=0)
y = Social_Network_Ads_DF.Purchased

In [344]:
# Prepare the train and test data

x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.head(3)

Age  EstimatedSalary
184   33            60000
18    46            28000
332   42            65000

In [346]:
# Create the model for MaxAbsScaler

from sklearn.preprocessing import MaxAbsScaler

# Create MaxAbsScaler object
MaxAbsScalerObj = MaxAbsScaler()

# Train with the traning data
MaxAbsScalerObj.fit(x_train)

MaxAbsScaler()

In [356]:
# Various attributes on MaxAbsScaler Object

MaxAbsScalerObj.scale_
#MaxAbsScalerObj.max_abs_
#MaxAbsScalerObj.n_features_in_

array([6.0e+01, 1.5e+05])

In [350]:
# Transform the data

x_train_scaled = MaxAbsScalerObj.transform(x_train)
x_test_scaled = MaxAbsScalerObj.transform(x_test)
x_test_scaled
# Output will be in numpy array format

array([[0.55      , 0.28666667],
       [0.5       , 0.9       ],
       [0.53333333, 0.12      ],
       [0.56666667, 0.28666667],
       [0.63333333, 0.43333333],
       [0.9       , 0.72      ],
       [0.86666667, 1.        ],
       [0.63333333, 0.40666667],
       [0.43333333, 0.34666667],
       [0.58333333, 0.39333333],
       [0.35      , 0.58666667],
       [0.43333333, 0.56      ],
       [0.61666667, 0.35333333],
       [0.41666667, 0.52666667],
       [0.46666667, 0.58      ],
       [0.81666667, 0.49333333],
       [0.48333333, 0.40666667],
       [0.53333333, 0.66666667],
       [0.86666667, 0.76      ],
       [0.58333333, 0.52666667],
       [0.5       , 0.58      ],
       [1.        , 0.28      ],
       [0.61666667, 0.5       ],
       [0.51666667, 0.1       ],
       [0.51666667, 0.44      ],
       [0.55      , 0.46      ],
       [0.81666667, 0.18666667],
       [0.45      , 0.91333333],
       [0.75      , 0.3       ],
       [0.3       , 0.29333333],
       [0.

In [358]:
# Convert the array to DataFrame

x_test_scaled_DF = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [366]:
x_test_scaled_DF.sort_values(by='EstimatedSalary',ascending=False)

Age  EstimatedSalary
6   0.866667         1.000000
49  0.700000         0.993333
65  0.850000         0.973333
37  0.600000         0.960000
32  0.883333         0.953333
..       ...              ...
52  0.533333         0.120000
2   0.533333         0.120000
62  0.450000         0.113333
90  0.433333         0.100000
23  0.516667         0.100000

[100 rows x 2 columns]