#### numpy - Numerical Python

In [5]:
# Hierarchy

# library > packages > modules > sub module > function

In [7]:
# Datastructure used in numpy is array
- Syntax:- numpy.array(list/tuple/dictionary)

# Array is identified as array([])

# string inside an array is called as object, all others are same, int, float, etc.

SyntaxError: illegal target for annotation (613243891.py, line 2)

In [9]:
# List to array 

import numpy as np
arr1 = np.array([2,4,6,2,1])
print(arr1)

mylist = [12,13,11]
arr2 = np.array(mylist)
print(arr2)

[2 4 6 2 1]
[12 13 11]


In [13]:
print("Type of arr1 is ",type(arr1))
print("Type of arr2 is ",type(arr2))

Type of arr1 is  <class 'numpy.ndarray'>
Type of arr2 is  <class 'numpy.ndarray'>


In [15]:
# ndarray refers to ndimensional array

In [17]:
# Array has to be created by using the list, tuple, set or dictionary 
arr2 = np.array(1,2,3,5)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [19]:
arr2 = np.array([1,2,3,5])

In [21]:
arr2

array([1, 2, 3, 5])

In [25]:
# Tuple to array 

import numpy as np
arr1 = np.array((2,4,6,2,1))
print(arr1)

mylist = (12,13,11)
arr2 = np.array(mylist)
print(arr2)

[2 4 6 2 1]
[12 13 11]


In [29]:
print("Type of arr1 is ",type(arr1))
print("Type of arr2 is ",type(arr2))

Type of arr1 is  <class 'numpy.ndarray'>
Type of arr2 is  <class 'numpy.ndarray'>


In [31]:
# Set to array 

import numpy as np
arr1 = np.array({2,4,6,2,1})
print(arr1)

mylist = {12,13,11}
arr2 = np.array(mylist)
print(arr2)

{1, 2, 4, 6}
{11, 12, 13}


In [33]:
print("Type of arr1 is ",type(arr1))
print("Type of arr2 is ",type(arr2))

Type of arr1 is  <class 'numpy.ndarray'>
Type of arr2 is  <class 'numpy.ndarray'>


In [35]:
# Dictionary to array 

import numpy as np
arr1 = np.array({1:'kk',2:'akk'})
print(arr1)

mylist = {1:'akk',3:'akkaaa'}
arr2 = np.array(mylist)
print(arr2)

{1: 'kk', 2: 'akk'}
{1: 'akk', 3: 'akkaaa'}


In [37]:
print("Type of arr1 is ",type(arr1))
print("Type of arr2 is ",type(arr2))

Type of arr1 is  <class 'numpy.ndarray'>
Type of arr2 is  <class 'numpy.ndarray'>


##### Note:-
- list/tuple/sets/dictionary - Can have heterogenus data
- array - Can have only homogenus data, if differernt data types are given to convert to array, it converts all elements to the same data type as per  the hierarchy.

In [46]:
# Homogenus list

list1 = [1,2,3,6]
list1

[1, 2, 3, 6]

In [48]:
# Homogenus list to array 

np.array(list1)

array([1, 2, 3, 6])

In [50]:
# Heterogenus list

list2 = [1,2,'kk',2.3]
list2

[1, 2, 'kk', 2.3]

In [54]:
# Heterogenus list to array 
# Since string carries the highest hirearchy, all the elements are converted to string.

np.array(list2)

array(['1', '2', 'kk', '2.3'], dtype='<U32')

In [56]:
np.array([1,'kk'])

array(['1', 'kk'], dtype='<U11')

In [58]:
list3 = [1,2,3.1,3.3,5]
list3

[1, 2, 3.1, 3.3, 5]

In [60]:
np.array(list3)

array([1. , 2. , 3.1, 3.3, 5. ])

In [78]:
tuple1 = (3,'kk',2.4)
tuple1

(3, 'kk', 2.4)

In [80]:
np.array(tuple1)

array(['3', 'kk', '2.4'], dtype='<U32')

In [82]:
set1 = {3,'kk',2.4}
set1

{2.4, 3, 'kk'}

In [84]:
np.array(set1)

array({2.4, 3, 'kk'}, dtype=object)