#### scalar and vector
dist and displacement
1d,2d,3d arrays

all above are 1d arrays

#### N Dimensional arrays

In [12]:
import numpy as np
list1 = [1,2,7,4,7]
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

[1 2 7 4 7]
<class 'numpy.ndarray'>


In [14]:
# ndim >>> To get the dimention of the array

arr1.ndim

1

In [28]:
# shape >>> To get the shape of the array

arr1.shape

(5,)

In [30]:
# size >>> To get the size of the array

arr1.size

5

In [50]:
list2 = [[2,4,6,8],[1,2,3,4]]
arr2 = np.array(list2)
print("Array is \n",arr2)
print("Type of the array is ",type(arr2))
print("Dimension of the array is ",arr2.ndim)
print("Shape of the arrays is ", arr2.shape)
print("Size of the array is ",arr2.size)

Array is 
 [[2 4 6 8]
 [1 2 3 4]]
Type of the array is  <class 'numpy.ndarray'>
Dimension of the array is  2
Shape of the arrays is  (2, 4)
Size of the array is  8


In [54]:
list3 = [[2, 4, 6, 8], [1, 2, 3, 4], [1, 3, 5, 7]]
arr3 = np.array(list3)
print("Array is \n",arr3)
print("Type of the array is ",type(arr3))
print("Dimension of the array is ",arr3.ndim)
print("Shape of the arrays is ", arr3.shape)
print("Size of the array is ",arr3.size)

Array is 
 [[2 4 6 8]
 [1 2 3 4]
 [1 3 5 7]]
Type of the array is  <class 'numpy.ndarray'>
Dimension of the array is  2
Shape of the arrays is  (3, 4)
Size of the array is  12


In [56]:
# Number of brackets = Number of dimentions of the array

In [58]:
list4 = [[[2, 4, 6, 8],[12, 14, 16, 18],[21, 41, 61, 81]],[[2, 4, 6, 8],[12, 14, 16, 18],[21, 41, 61, 81]]]
arr4 = np.array(list4)
print("Array is \n",arr4)
print("Type of the array is ",type(arr4))
print("Dimension of the array is ",arr4.ndim)
print("Shape of the arrays is ", arr4.shape)
print("Size of the array is ",arr4.size)

Array is 
 [[[ 2  4  6  8]
  [12 14 16 18]
  [21 41 61 81]]

 [[ 2  4  6  8]
  [12 14 16 18]
  [21 41 61 81]]]
Type of the array is  <class 'numpy.ndarray'>
Dimension of the array is  3
Shape of the arrays is  (2, 3, 4)
Size of the array is  24


In [64]:
list5 = [
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ],
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ],
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ]
]
arr5 = np.array(list5)
print("Array is \n",arr5)
print("Type of the array is ",type(arr5))
print("Dimension of the array is ",arr5.ndim)
print("Shape of the arrays is ", arr5.shape)
print("Size of the array is ",arr5.size)

Array is 
 [[[ 2  4  6]
  [12 14 16]
  [21 41 61]
  [22 24 26]
  [22 42 62]]

 [[ 2  4  6]
  [12 14 16]
  [21 41 61]
  [22 24 26]
  [22 42 62]]

 [[ 2  4  6]
  [12 14 16]
  [21 41 61]
  [22 24 26]
  [22 42 62]]]
Type of the array is  <class 'numpy.ndarray'>
Dimension of the array is  3
Shape of the arrays is  (3, 5, 3)
Size of the array is  45


In [68]:
# Create 2 3 5 3 matrix
list6 = [
[
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ],
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ],
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ]
],
    [
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ],
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ],
    [
        [2, 4, 6],[12, 14, 16],[21, 41, 61],[22, 24, 26],[22, 42, 62]
    ]
]
]
arr6 = np.array(list6)
print("Array is \n",arr6)
print("Type of the array is ",type(arr6))
print("Dimension of the array is ",arr6.ndim)
print("Shape of the arrays is ", arr6.shape)
print("Size of the array is ",arr6.size)

Array is 
 [[[[ 2  4  6]
   [12 14 16]
   [21 41 61]
   [22 24 26]
   [22 42 62]]

  [[ 2  4  6]
   [12 14 16]
   [21 41 61]
   [22 24 26]
   [22 42 62]]

  [[ 2  4  6]
   [12 14 16]
   [21 41 61]
   [22 24 26]
   [22 42 62]]]


 [[[ 2  4  6]
   [12 14 16]
   [21 41 61]
   [22 24 26]
   [22 42 62]]

  [[ 2  4  6]
   [12 14 16]
   [21 41 61]
   [22 24 26]
   [22 42 62]]

  [[ 2  4  6]
   [12 14 16]
   [21 41 61]
   [22 24 26]
   [22 42 62]]]]
Type of the array is  <class 'numpy.ndarray'>
Dimension of the array is  4
Shape of the arrays is  (2, 3, 5, 3)
Size of the array is  90
