In [4]:
# Arrange method - to create an array with the start value, end value(not included) and an increment

import numpy as np
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [10]:
np.arange(100,1000,50)

array([100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700,
       750, 800, 850, 900, 950])

In [12]:
# Create an array with only zeros
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# Create an array with only one
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# Create an array with random numbers
np.random.random(10)

array([0.40847539, 0.44790949, 0.06957339, 0.21027855, 0.45374975,
       0.85778831, 0.44319524, 0.56856955, 0.41045688, 0.21369682])

In [ ]:
# This does not create array, just a random number
np.random.randint(10)

In [39]:
# Create an array with random integers
np.random.randint(1,100,24)

array([17, 45, 35, 97, 63, 48, 73, 13, 50, 17, 87, 16, 80, 28, 40, 10, 58,
        3, 15, 42, 71, 42, 13, 45])

In [32]:
# Create an array starting with 10 and ending with 100 and with only 5 numbers with equal spacing
np.linspace(10,100,5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [34]:
np.linspace(10,100,4)

array([ 10.,  40.,  70., 100.])

In [36]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [47]:
# Create an array with random integers
arr1 = np.random.randint(1,100,24)

In [49]:
# Reshape the array to 12*2 >>> 2 elements * 12 rows

arr1.reshape(12,2)

array([[65, 27],
       [43, 95],
       [66, 23],
       [87, 46],
       [37, 24],
       [97, 51],
       [11, 46],
       [86,  4],
       [86,  5],
       [30, 71],
       [55,  2],
       [40, 15]])

In [51]:
# Reshape the array to 12*2 >>> 12 elements * 2 rows

arr1.reshape(2,12)

array([[65, 27, 43, 95, 66, 23, 87, 46, 37, 24, 97, 51],
       [11, 46, 86,  4, 86,  5, 30, 71, 55,  2, 40, 15]])

In [55]:
# Reshape the array to 2*3*4 >>> Note that the total elements should match the multiplication value

arr1.reshape(2,3,4)

array([[[65, 27, 43, 95],
        [66, 23, 87, 46],
        [37, 24, 97, 51]],

       [[11, 46, 86,  4],
        [86,  5, 30, 71],
        [55,  2, 40, 15]]])

In [59]:
# Create an array with 0 to 23 and reshape with 2 elements with 12 rows
np.arange(24)
#np.arange(24).reshape(12,2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [61]:
np.arange(24).reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [63]:
np.arange(0,24,1).reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [65]:
np.arange(0,24,1).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])