In [46]:
# Create an array from 1 to 22 and then

import numpy as np
arr1 = np.arange(1,23,1)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

#### Slicing from 1D array

In [48]:
# extract only 10

arr1[9]

10

In [50]:
# extract 17 to 22

print(arr1[16:])
print(arr1[16:23])
print(arr1[16:22])
print(arr1[16:21])

[17 18 19 20 21 22]
[17 18 19 20 21 22]
[17 18 19 20 21 22]
[17 18 19 20 21]


In [66]:
# Create an array from 1 to 23 and then

import numpy as np
arr2 = np.arange(0,24,1)
#arr2 = np.arange(24)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
# get only 16
print(arr2[16])

# get from 16 tilll 23
print(arr2[16:])

# Guess the output
print(arr2[16:1])

# Get from 16 till 22
print(arr2[16:-1])
# from 16 till -1-1 = -2 i.e. 22
print(arr2[16:23])

# Get from 16 till 21
print(arr2[16:-2])
print(arr2[16:22])

16
[16 17 18 19 20 21 22 23]
[]
[16 17 18 19 20 21 22]
[16 17 18 19 20 21 22]
[16 17 18 19 20 21]
[16 17 18 19 20 21]


### Slicing from 2D array

In [76]:
# Create an array with elements from 0 to 23 using arange and then convert it to 2*12 elements

arr3 = np.arange(24).reshape(2,12)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [82]:
# Get the 1st row completely
arr3[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
# Get the 2nd row completely
arr3[1]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [86]:
# Get values from 12 to 17
arr3[1][0:6]

array([12, 13, 14, 15, 16, 17])

In [90]:
# Get value 21
arr3[1][9]

21

In [92]:
# Get values from 13 to 18
arr3[1][1:7]

array([13, 14, 15, 16, 17, 18])

#### Slicing from 3D array

In [101]:
# Create a 3D with values from 0 to 23 of size 4,2,3

arr4 = np.arange(24).reshape(4,2,3)
arr4

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [103]:
# Extract [[ 0,  1,  2],
#        [ 3,  4,  5]]

arr4[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [105]:
# Extract [9 10 11]

arr4[1][1]

array([ 9, 10, 11])

In [107]:
# Extract only 18 and 19
arr4[3][0][0:2]

array([18, 19])

In [109]:
# Extract only 16
arr4[2][1][1]

16

In [117]:
# Extract only 13 and 14
print(arr4[2][0][1:3])
print(arr4[2][0][1:])

[13 14]
[13 14]


In [127]:
# Create array from 0 to 15 and then extract values that are > 12
arr5 = np.arange(16)
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [131]:
for i in arr5:
    if i > 12:
        print(i)

13
14
15


#### boolean mask

In [143]:
arr5[True]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [145]:
arr5[False]

array([], shape=(0, 16), dtype=int32)

In [147]:
arr5 > 12

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True])

In [149]:
arr5[arr5>12]

array([13, 14, 15])

#### Slicing using for loop in 1D, 2D, 3D, etc. arrays

In [184]:
# Create 1D array from 0 to 8 and then print values one by one
arr1d = np.arange(9)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [186]:
for i in arr1d:
    print(i)

0
1
2
3
4
5
6
7
8


In [196]:
# Create 2D array from 0 to 9 of 3*3 and print each row
arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [198]:
# print each row separately
for i in arr2d:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]


In [200]:
# print each element separately from above 2D array
for i in arr2d:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8


In [202]:
# Print only 5
for i in arr2d:
    for j in i:
        if j == 5:
            print(j)

5
