In [1]:
# Create two 1D arrays, one with numbers from 0 to 7 and the other from 8 to 15

import numpy as np
a1 = np.arange(8)
a2 = np.arange(8,16)
print(a1)
print(a2)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [3]:
# Add both the arrays
print(a1)
print(a2)
print("Addition of array 1 and array 2 is ",a1 + a2)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
Addition of array 1 and array 2 is  [ 8 10 12 14 16 18 20 22]


In [41]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)

arr2 = np.array([[2,3,4],[5,6,7]])
print(arr2)

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]


In [43]:
arr1 + arr2

array([[ 3,  5,  7],
       [ 9, 11, 13]])

##### Note:- 
- For addition both the sizes/dimentions should be same
- For multiplication (x,y) * (y,z) = (x,z), y should always match for both the arrays

In [7]:
# Multiplication of both the arrays
print(a1)
print(a2)
print("Multiplication of array 1 and array 2 is ",a1 * a2)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
Multiplication of array 1 and array 2 is  [  0   9  20  33  48  65  84 105]


In [9]:
# Square of the arrays
print(a1)
print("Square of array 1 is ",a1 ** 2)
print(a2)
print("Square of array 2 is ",a2 ** 2)

[0 1 2 3 4 5 6 7]
Square of array 1 is  [ 0  1  4  9 16 25 36 49]
[ 8  9 10 11 12 13 14 15]
Square of array 2 is  [ 64  81 100 121 144 169 196 225]


In [11]:
# Square root of array 1
print(a1)
print("Square root of array 1 is ",np.sqrt(a1))

[0 1 2 3 4 5 6 7]
Square root of array 1 is  [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131]


#### dot product
2\*3
3\*4
dot product = 2\*4

In [17]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print("\n")
print(b)
print("\n")
print(np.dot(a,b))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [19]:
'''
Note: Output of (x,y) * (y,z) = (x,z) size array. y should always match for multiplication

[0 1 2 3] * 
[
0
3
6
9
]
= 0*0 + 1*3 + 2*6 + 3*9 = 0 + 3 + 12 + 27 = 42

[0  1  2  3]
[1 4 7 10]
= 0*1 + 1*4 + 2 * 7 + 3 * 10 = 0+4+14+30 = 48

so on

last one
[ 8  9 10 11] * [2 5 8 11] = 8*2 + 9*5 + 10*8 + 11*11 = 16+45+80+121 = 262'''

'\nNote: Output of (x,y) * (y,z) = (x,z) size array. y should always match for multiplication\n\n[0 1 2 3] * \n[\n0\n3\n6\n9\n]\n= 0*0 + 1*3 + 2*6 + 3*9 = 0 + 3 + 12 + 27 = 42\n\n[0  1  2  3]\n[1 4 7 10]\n= 0*1 + 1*4 + 2 * 7 + 3 * 10 = 0+4+14+30 = 48\n\nso on\n\nlast one\n[ 8  9 10 11] * [2 5 8 11] = 8*2 + 9*5 + 10*8 + 11*11 = 16+45+80+121 = 262'

### broadcasting
- If addtion/substraction try to make both the arrays as same dimension
- If multiplication try to make both the arrays as 

In [49]:
# Add a scalar value (single value) to an vector (array)

arr1 = np.array([1,2,3])
print(arr1)
print(arr1 + 2)

[1 2 3]
[3 4 5]


In [53]:
'''
In background
[1 2 3] + 2 is getting added to each element.
= [1 2 3] + [2 2 2]
= [1+2 2+2 3+2]
= [3 4 5]
'''

'\nIn background\n[1 2 3] + 2 is getting added to each element.\n= [1 2 3] + [2 2 2]\n= [1+2 2+2 3+2]\n= [3 4 5]\n'

In [71]:
# Add a single value(1*1) array, to 1*3 array

arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([2])
print(arr2)
print(arr1 + arr2)

[1 2 3]
[2]
[3 4 5]


In [69]:
# Add an array of 1*2, to 1*3 array

arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([2,3])
print(arr2)
print(arr1 + arr2)

[1 2 3]
[2 3]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [75]:
arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([[2],[4],[6]])
print(arr2)
print(arr1 + arr2)

[1 2 3]
[[2]
 [4]
 [6]]
[[3 4 5]
 [5 6 7]
 [7 8 9]]


In [77]:
""""
1 2 3
# 1*3
# Since the dimension is 1, it will be changed to

2
4
6
# 3*1

1 2 3
1 2 3
1 2 3
# 3*3

2 2 2
4 4 4
6 6 6
# 3*3
"""

'"\n1 2 3\n# 1*3\n\n2\n4\n6\n# 3*1\n\n1 2 3\n1 2 3\n1 2 3\n\n2 2 2\n4 4 4\n6 6 6\n'

In [85]:
arr1 = np.array([1,2,3]) #1*3
arr2 = np.array([4,5,6,7]) #1*4
arr1+arr2
# Won't work as both cannot be converted to same shape/dimension

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [87]:
arr1 = np.array([[1,2,3],[4,5,6]]) #2*3 2D array
arr2 = np.array([4,2,2]) #1*3 1D array
arr1+arr2

array([[5, 4, 5],
       [8, 7, 8]])

In [ ]:
"""
1 2 3
4 5 6
#2*3

4 2 2
# 1*3
Since one of the dimension is 1, it will be changed to 

1 2 3
4 5 6

4 2 2
4 2 2

In [95]:
arr1 = np.array([[1,2],[3,4],[5,6]]) #3*2
arr2 = np.array([2,2,2]) #3*1
arr1+arr2

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
'''
1 2
3 4
5 6
# 3*2

2 2 2
# 1*3
# Since of the dimension is 1, it tries to convert this array to 3*2

1 2
3 4
5 6
# 3*2

2 2 2
2 2 2
2 2 2
# 3*3
But still, it doesn't match after converting, hence broadcasting doesn't work here
'''

In [97]:
import numpy as np
a = np.arange(12).reshape(3,4)

In [99]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
b = np.arange(12,24).reshape(4,3)
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [103]:
a * b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [105]:
a + b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [107]:
c = np.arange(4)

In [109]:
print(a)
print("\n")
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[0 1 2 3]


In [ ]:
''''
[ 0  1  2  3]
[ 4  5  6  7]
[ 8  9 10 11]

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]

''''

In [111]:
a+c

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [121]:
a = np.arange(16).reshape(4,4)
b = np.arange(32,48).reshape(4,2,2)

print(a)
print("\n")
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[[32 33]
  [34 35]]

 [[36 37]
  [38 39]]

 [[40 41]
  [42 43]]

 [[44 45]
  [46 47]]]


In [123]:
a+b

ValueError: operands could not be broadcast together with shapes (4,4) (4,2,2) 

In [125]:
a = np.arange(16).reshape(8,2)
b = np.arange(32,48)

print(a)
print("\n")
print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


[32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [127]:
a + b 

ValueError: operands could not be broadcast together with shapes (8,2) (16,) 

In [129]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print("\n")
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [131]:
a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [147]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print("\n")
print(b)

[[0 1 2]]


[[0]
 [1]
 [2]]


In [153]:
'''
0 1 2
#1*3

0
1
2
#3*1

both the arrays can be converted to match the dimensions
0 1 2
0 1 2
0 1 2

0 0 0
1 1 1
2 2 2
'''

'\n0 1 2\n#1*3\n\n0\n1\n2\n#3*1\n\nboth the arrays can be converted to match the dimensions\n0 1 2\n0 1 2\n0 1 2\n\n0 0 0\n1 1 1\n2 2 2\n'

In [155]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])