In [4]:
import numpy as np
d = np.arange(30).reshape(6,5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
# Get only 2nd column values
d[:,1]

array([ 1,  6, 11, 16, 21, 26])

In [38]:
# Get only 4th column values 
d[:,3]

array([ 3,  8, 13, 18, 23, 28])

In [40]:
# Get only 2nd, 4th and 5th column values
d[:,[1,3,4]]

array([[ 1,  3,  4],
       [ 6,  8,  9],
       [11, 13, 14],
       [16, 18, 19],
       [21, 23, 24],
       [26, 28, 29]])

In [44]:
# Get only 2nd, 4th and 5th row values
d[[1,3,4]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
# Extract only 11 16 and 26
d[[2,3,5],[1]]

array([11, 16, 26])

#### Pass Arrays to a function

In [63]:
# Create a function to add 5 numbers
add = lambda a,b,c,d,e : a+b+c+d+e
add(1,2,3,4,5)

15

In [71]:
# Create an array from 0 to 5 and find the square of each
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [73]:
sqr_arr1 = lambda a: a**2
sqr_arr1(arr1)

array([ 0,  1,  4,  9, 16, 25])

In [77]:
# Sigmoid activation function using arrays and normal function
# σ(x) = 1 / (1 + e^(-x)), where x is the input of arrays and e is Euler's number
# Pass numbers from 0 to 5 to sigmoid function from an array

def sigmoid(x):
    return 1/(1 + np.exp(-x))

nums = np.arange(6)
sigmoid(nums)

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715])

In [85]:
# Same function using lambda

sigmoid = lambda x : 1/(1 + np.exp(-x))
sigmoid(np.arange(6))

array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715])